package com.example.smmoney.importexport.ofx;

class OFX_Tags {
    String accountBegin;
    String accountEnd;
    String accountIDBegin;
    String accountIDEnd;
    String accountTypeBegin;
    String accountTypeEnd;
    String availableBalanceBegin;
    String availableBalanceEnd;
    String balanceAmountBegin;
    String balanceAmountEnd;
    String bankIDBegin;
    String bankIDEnd;
    String bankStatementTransmissionBegin;
    String bankStatementTransmissionEnd;
    String bankTransListBegin;
    String bankTransListEnd;
    String creditCardAccountBegin;
    String creditCardAccountEnd;
    String creditCardStatementTransmissionBegin;
    String creditCardStatementTransmissionEnd;
    String currencyBegin;
    String currencyEnd;
    String dateAsOfBegin;
    String dateAsOfEnd;
    String dateEndBegin;
    String dateEndEnd;
    String dateStartBegin;
    String dateStartEnd;
    String ledgerBalanceBegin;
    String ledgerBalanceEnd;
    final String lineEnding;
    String statusBegin;
    String statusCodeBegin;
    String statusCodeEnd;
    String statusEnd;
    String statusMessageBegin;
    String statusMessageEnd;
    String statusSeverityBegin;
    String statusSeverityEnd;
    String transactionAmountBegin;
    String transactionAmountEnd;
    String transactionBegin;
    String transactionCheckNumBegin;
    String transactionCheckNumEnd;
    String transactionDatePostedBegin;
    String transactionDatePostedEnd;
    String transactionDateUserEnteredBegin;
    String transactionDateUserEnteredEnd;
    String transactionEnd;
    String transactionFitIDBegin;
    String transactionFitIDEnd;
    String transactionMemoBegin;
    String transactionMemoEnd;
    String transactionNameBegin;
    String transactionNameEnd;
    String transactionTypeBegin;
    String transactionTypeEnd;

    OFX_Tags(OFX_DataFormatType theFormat, String lineEnding) {
        this.lineEnding = lineEnding;
        this.setFormat(theFormat);
    }

    private void setFormat(OFX_DataFormatType aFormat) {
        this.bankStatementTransmissionBegin = "<STMTRS>";
        this.bankStatementTransmissionEnd = "</STMTRS>";
        this.creditCardStatementTransmissionBegin = "<CCSTMTRS>";
        this.creditCardStatementTransmissionEnd = "</CCSTMTRS>";
        this.statusBegin = "<STATUS>";
        this.statusEnd = "</STATUS>";
        this.statusCodeBegin = "<CODE>";
        this.statusCodeEnd = "";
        this.statusSeverityBegin = "<SEVERITY>";
        this.statusSeverityEnd = "";
        this.statusMessageBegin = "<MESSAGE>";
        this.statusMessageEnd = "";
        this.currencyBegin = "<CURDEF>";
        this.currencyEnd = "";
        this.accountBegin = "<BANKACCTFROM>";
        this.accountEnd = "</BANKACCTFROM>";
        this.creditCardAccountBegin = "<CCACCTFROM>";
        this.creditCardAccountEnd = "</CCACCTFROM>";
        this.dateStartBegin = "<DTSTART>";
        this.dateStartEnd = "";
        this.dateEndBegin = "<DTEND>";
        this.dateEndEnd = "";
        this.ledgerBalanceBegin = "<LEDGERBAL>";
        this.ledgerBalanceEnd = "</LEDGERBAL>";
        this.availableBalanceBegin = "<AVAILBAL>";
        this.availableBalanceEnd = "</AVAILBAL>";
        this.bankTransListBegin = "<BANKTRANLIST>";
        this.bankTransListEnd = "</BANKTRANLIST>";
        this.transactionBegin = "<STMTTRN>";
        this.transactionEnd = "</STMTTRN>";
        this.bankIDBegin = "<BANKID>";
        this.bankIDEnd = "";
        this.accountIDBegin = "<ACCTID>";
        this.accountIDEnd = "";
        this.accountTypeBegin = "<ACCTTYPE>";
        this.accountTypeEnd = "";
        this.balanceAmountBegin = "<BALAMT>";
        this.balanceAmountEnd = "";
        this.dateAsOfBegin = "<DTASOF>";
        this.dateAsOfEnd = "";
        this.transactionTypeBegin = "<TRNTYPE>";
        this.transactionTypeEnd = "";
        this.transactionAmountBegin = "<TRNAMT>";
        this.transactionAmountEnd = "";
        this.transactionCheckNumBegin = "<CHECKNUM>";
        this.transactionCheckNumEnd = "";
        this.transactionNameBegin = "<NAME>";
        this.transactionNameEnd = "";
        this.transactionFitIDBegin = "<FITID>";
        this.transactionFitIDEnd = "";
        this.transactionMemoBegin = "<MEMO>";
        this.transactionMemoEnd = "";
        this.transactionDatePostedBegin = "<DTPOSTED>";
        this.transactionDatePostedEnd = "";
        this.transactionDateUserEnteredBegin = "<DTUSER>";
        this.transactionDateUserEnteredEnd = "";
        if (OFX_DataFormatType.OFX_DataFormatXML10 == aFormat || OFX_DataFormatType.OFX_DataFormatXML20 == aFormat) {
            this.currencyEnd = "</CURDEF>";
            this.dateStartEnd = "</DTSTART>";
            this.dateEndEnd = "</DTEND>";
            this.statusCodeEnd = "</CODE>";
            this.statusSeverityEnd = "</SEVERITY>";
            this.statusMessageEnd = "</MESSAGE>";
            this.bankIDEnd = "</BANKID>";
            this.accountIDEnd = "</ACCTID>";
            this.accountTypeEnd = "</ACCTTYPE>";
            this.balanceAmountEnd = "</BALAMT>";
            this.dateAsOfEnd = "</DTASOF>";
            this.transactionTypeEnd = "</TRNTYPE>";
            this.transactionAmountEnd = "</TRNAMT>";
            this.transactionCheckNumEnd = "</CHECKNUM>";
            this.transactionNameEnd = "</NAME>";
            this.transactionFitIDEnd = "</FITID>";
            this.transactionMemoEnd = "</MEMO>";
            this.transactionDatePostedEnd = "</DTPOSTED>";
            this.transactionDateUserEnteredEnd = "</DTUSER>";
        }

    }
}
